import { EventFormData } from "@/src/modules/business/types/event";

export interface DraftEvent extends EventFormData {
  id: string;
  createdAt: string;
  status: "draft" | "preview" | "published";
}

const draftEventsStore: DraftEvent[] = [];

export const addDraftEvent = (formData: EventFormData): DraftEvent => {
  const draftEvent: DraftEvent = {
    ...formData,
    id: `draft-${Date.now()}`,
    createdAt: new Date().toISOString(),
    status: "preview",
  };
  draftEventsStore.push(draftEvent);
  return draftEvent;
};

export const getDraftEventById = (id: string): DraftEvent | undefined => {
  return draftEventsStore.find((event) => event.id === id);
};

export const updateDraftEventStatus = (id: string, status: DraftEvent["status"]): void => {
  const event = draftEventsStore.find((e) => e.id === id);
  if (event) {
    event.status = status;
  }
};

export const getAllDraftEvents = (): DraftEvent[] => {
  return [...draftEventsStore];
};

export const TEST_DATABASE = {
  categorias: [
    { id: 1, nombre: "Cultura" },
    { id: 2, nombre: "Música" },
    { id: 3, nombre: "Ferias" },
    { id: 4, nombre: "Arte" },
    { id: 5, nombre: "Danza" },
  ],
  usuarios: [
    {
      id: 1001,
      email: "anahi@llajtazo.com",
      nombre_completo: "Anahi Zambrano",
      password_hash: "$2b$10$dummylLajtazoHashPass123456789abcdefghijk",
      plain_password: "pass123",
      avatar_url: require("@/src/core/test/assets/user-profile.png"),
      created_at: "2024-07-12T14:23:00Z",
      bio: "Estoy usando Llajtazo App para descubrir eventos increibles cerca de mi",
      isVinculated: false,
      business_organizer_id: null,
    },
  ],
  organizadores: [
    {
      id: 499,
      nombre: "Broadway Bolivia",
      email: "broadway@broadway.com",
      username: "broadway",
      password: "password123",
      verificationCode: "1234",
      about: "Organizador de eventos",
      bio: "Broadway Bolivia es una plataforma dedicada a la promoción y organización de eventos culturales y artísticos en Bolivia, ofreciendo una variedad de espectáculos que incluyen teatro, música y danza.",
      logo_url: require("@/src/core/assets/events/broadway/profile.png"),
      followers: 9789,
      following: 185,
      isPlus: false,
      socialLinks: [
        { type: "instagram", url: "https://instagram.com/BroadwayBolivia" },
        { type: "facebook", url: "https://facebook.com/BroadwayBolivia" },
        { type: "twitter", url: "https://twitter.com/BroadwayBolivia" },
      ],
      suscribed: 1,
    },
    {
      id: 498,
      nombre: "Danzares",
      email: "danzares@danzares.com",
      username: "danzares",
      password: "password123",
      verificationCode: "1234",
      about: "Organizador de eventos",
      bio: "Danzares es una compañía dedicada a la promoción y producción de eventos de danza contemporánea y clásica en Bolivia, ofreciendo espectáculos que fusionan tradición y modernidad.",
      logo_url: require("@/src/core/assets/events/danzares/profile.png"),
      followers: 2896,
      following: 185,
      isPlus: false,
      socialLinks: [
        { type: "instagram", url: "https://instagram.com/Danzares" },
        { type: "facebook", url: "https://facebook.com/Danzares" },
        { type: "twitter", url: "https://twitter.com/Danzares" },
      ],
      suscribed: 1,
    },
{
      id: 497,
      nombre: "Fundación Patino",
      email: "fundacionpatino@fundacionpatino.com",
      username: "fundacionpatino",
      password: "password123",
      verificationCode: "1234",
      about: "Organizador de eventos",
      bio: "Fundación Patino es una organización dedicada a la promoción y apoyo de eventos culturales y artísticos en Bolivia, fomentando el desarrollo de la comunidad a través del arte.",
      logo_url: require("@/src/core/assets/events/fundacion-patino/profile.png"),
      followers: 11478,
      following: 376,
      isPlus: false,
      socialLinks: [
        { type: "instagram", url: "https://instagram.com/FundacionPatino" },
        { type: "facebook", url: "https://facebook.com/FundacionPatino" },
        { type: "twitter", url: "https://twitter.com/FundacionPatino" },
      ],
      suscribed: 1,
    },
    {
      id: 500,
      nombre: "Euphoria",
      email: "euphoria@euphoria.com",
      username: "euphoria",
      password: "password123",
      verificationCode: "1234",
      about: "Organizador de eventos",
      bio: "Euphoria es un espacio dedicado a la música electrónica y la cultura urbana, ofreciendo eventos inolvidables con los mejores DJs y artistas del momento.",
      logo_url: require("@/src/core/assets/events/euphoria/profile.png"),
      followers: 15789,
      following: 485,
      isPlus: false,
      socialLinks: [
        { type: "instagram", url: "https://instagram.com/Euphoria" },
        { type: "facebook", url: "https://facebook.com/Euphoria" },
        { type: "twitter", url: "https://twitter.com/Euphoria" },
      ],
      suscribed: 1,
    },
    {
      id: 501,
      nombre: "NOMA",
      email: "noma@noma.com",
      username: "noma",
      password: "password123",
      verificationCode: "1234",
      about: "Organizador de eventos",
      bio: "Un espacio para vivir experiencias que no podrían ser vividas en otros lugares. NOMA es más que un lugar, es una comunidad de amantes de la música, el arte y la cultura.",
      logo_url: require("@/src/core/assets/events/noma/profile.png"),
      followers: 10589,
      following: 274,
      isPlus: false,
      socialLinks: [
        { type: "instagram", url: "https://instagram.com/NOMALounge" },
        { type: "facebook", url: "https://facebook.com/NOMALounge" },
        { type: "twitter", url: "https://twitter.com/NOMALounge" },
      ],
      suscribed: 1,
    },
    {
      id: 502,
      nombre: "Alice Park",
      email: "alice@alicepark.com",
      username: "alicepark",
      password: "password123",
      verificationCode: "1234",
      about: "Organizador de eventos",
      bio: "Alice Park es la discoteca más grande y moderna de Bolivia, inaugurada en 2024 en Cochabamba con un show internacional de Lunay y respaldada por Amstel Beer.",
      logo_url: require("@/src/core/assets/events/alice-park/profile.jpg"),
      followers: 12756,
      following: 350,
      isPlus: false,
      socialLinks: [
        { type: "instagram", url: "https://instagram.com/alicepark" },
        { type: "facebook", url: "https://facebook.com/alicepark" },
        { type: "twitter", url: "https://twitter.com/alicepark" },
      ],
      suscribed: 1,
    },
        {
      id: 503,
      nombre: "Levitar",
      email: "levitar@levitar.com",
      username: "levitar",
      password: "password123",
      verificationCode: "1234",
      about: "Organizador de eventos",
      bio: "Levitar es un espacio dedicado a la música electrónica y la cultura urbana, ofreciendo eventos inolvidables con los mejores DJs y artistas del momento.",
      logo_url: require("@/src/core/assets/events/levitar/profile.png"),
      followers: 5896,
      following: 125,
      isPlus: false,
      socialLinks: [
        { type: "instagram", url: "https://instagram.com/levitar" },
        { type: "facebook", url: "https://facebook.com/levitar" },
        { type: "twitter", url: "https://twitter.com/levitar" },
      ],
      suscribed: 1,
    },
  ],
  lugares: [
    {
      id: 701,
      nombre: "Alice Park",
      direccion: "Av. Melchor Urquidi, Cochabamba",
      latitud: -17.376642360467393,
      longitud: -66.14978895823978,
    },
    {
      id: 702,
      nombre: "NOMA",
      direccion: "Av. Melchor Urquidi, Cochabamba",
      latitud: -17.3755683230705,
      longitud: -66.14949157866889,
    },
    {
      id: 703,
      nombre: "Teatro Acha",
      direccion: "Calle Esteban Arze, Cochabamba",
      latitud: -17.392594702617355,
      longitud: -66.15679335995263,
    },
    {
      id: 704,
      nombre: "Palacio Portales",
      direccion: "Calle Potosi, Cochabamba",
      latitud: -17.374738371256882,
      longitud:  -66.15305735006453,
    },
    {
      id: 705,
      nombre: "Euphoria",
      direccion: "Av. Melchor Urquidi, Cochabamba",
      latitud: -17.372449134382894, 
      longitud: -66.14941836180617,
    },
    {
      id: 706,
      nombre: "Fexco",
      direccion: "Circuito Bolivia, Cochabamba",
      latitud: -17.420097536356298, 
      longitud: -66.12946610226996, 
    }

  ],
  events: [
    {
      id: 901,
      organizador_id: 502,
      lugar_id: 701,
      categoria_id: 1,
      titulo: "C.R.O en concierto",
      slug: "cro",
      subtitulo: "",
      descripcion: "<p>🎤🔥 ¡CRO (CRO Oficial) llega a Cochabamba! Seguimos con el modo diablo y ahora el príncipe de la movida aterriza en Alice Park para una noche épica.<br/><br/>Prepárate para vibrar con los hits que revolucionaron la escena del trap latino. 🕺💃<br/><br/>Capacidad limitada y las almas listas para el delirio.<br/>¡11 de abril en Cochabamba, Bolivia 🇧🇴!<br/><br/>No te quedes fuera.</p>",
      start_time: "2025-04-11T21:00:00Z",
      cover_url: require("@/src/core/assets/events/alice-park/event6.jpg"),
      attendeesCount: 200,
      totalSales: 15760.8,
      ticketsSold: 856,
      tickets: [
      {
        id: "ticket-rockstar",
        name: "ROCKSTAR",
        price: 150,
        currency: "Bs.",
        available: false,
        isSoldOut: true,
      },
      {
        id: "ticket-campo",
        name: "CAMPO",
        price: 200,
        currency: "Bs.",
        available: true,
        isSoldOut: false,
      },
      {
        id: "ticket-terraza",
        name: "TERRAZA",
        price: 250,
        currency: "Bs.",
        available: true,
        isSoldOut: false,
      },
  ],
      sectorImageUrl: require("@/src/core/assets/events/alice-park/SECTORES.png"),
      spotifyPlaylistUrl: "https://open.spotify.com/playlist/37i9dQZF1E4ovNoe2bZiyz?utm_source=generator",
      youtubeVideoUrl: "",
      estado: "PUBLISHED",
    },
{
  id: 902,
  organizador_id: 502,
  lugar_id: 701,
  categoria_id: 2,
  titulo: "Lu de la Tower & Corona – After Bautizo",
      slug: "corona-lu",
  subtitulo: "",
  descripcion: "<p>Una noche especial con Lu de la Torre y Corona. Música urbana, energía joven y fiesta garantizada.</p>",
  start_time: "2025-09-20T21:00:00Z",
  cover_url:require("@/src/core/assets/events/alice-park/event5.jpg"),
  attendeesCount: 0,
   totalSales: 25879.8,
    ticketsSold: 896,
  tickets: [
    { id: "ticket-general-lu", name: "Entrada General", price: 60, currency: "Bs.", available: true, isSoldOut: false },
    { id: "ticket-after-lu", name: "After Early Access", price: 90, currency: "Bs.", available: true, isSoldOut: false },
  ],
  sectorImageUrl: "",
  spotifyPlaylistUrl: "https://open.spotify.com/embed/playlist/37i9dQZF1DZ06evO3ynUWg?utm_source=generator&theme=0", // L-Gante y Cumbia Playlist 🎧 :contentReference[oaicite:2]{index=2}
  youtubeVideoUrl: "",
  estado: "PUBLISHED",
},
{
  id: 903,
  organizador_id: 502,
  lugar_id: 701,
  categoria_id: 2,
  titulo: "L-Gante – Keloke",
    slug: "lgante",
  subtitulo: "",
  descripcion: "<p>El fenómeno de la cumbia 420 llega a Cochabamba para un show único en Alice Park.</p>",
  start_time: "2025-12-12T21:00:00Z",
  cover_url: require("@/src/core/assets/events/alice-park/event1.png"),
  attendeesCount: 0,
   totalSales: 31896.8,
    ticketsSold: 963,
  tickets: [
    { id: "ticket-general-lgante", name: "Entrada General", price: 380, currency: "Bs.", available: true, isSoldOut: false },
    { id: "ticket-vip-lgante", name: "VIP Front Stage", price: 550, currency: "Bs.", available: true, isSoldOut: false },
  ],
  sectorImageUrl: "",
  spotifyPlaylistUrl: "https://open.spotify.com/embed/playlist/37i9dQZF1DZ06evO2Vr1qU?utm_source=generator&theme=0", // L-Gante Top 10 🎧 :contentReference[oaicite:3]{index=3}
  youtubeVideoUrl: "",
  estado: "PUBLISHED",
},
{
  id: 904,
  organizador_id: 502,
  lugar_id: 701,
  categoria_id: 2,
  titulo: "BRESH – Bolivia",
    slug: "bresh",
  subtitulo: "",
  descripcion: "<p>La fiesta más linda del mundo llega a Cochabamba. Edición especial en Alice Park.</p>",
  start_time: "2025-12-27T21:00:00Z",
  cover_url: require("@/src/core/assets/events/alice-park/event2.png"),
  attendeesCount: 0,
   totalSales: 25879.8,
    ticketsSold: 674,
  tickets: [
    { id: "ticket-general-bresh", name: "Entrada General", price: 70, currency: "Bs.", available: true, isSoldOut: false },
    { id: "ticket-vip-bresh", name: "VIP Bresh Lounge", price: 130, currency: "Bs.", available: true, isSoldOut: false },
  ],
  sectorImageUrl: "",
  spotifyPlaylistUrl: "https://open.spotify.com/embed/playlist/7ofxoTvvs37VHrCoU9RvOa?utm_source=generator",
  youtubeVideoUrl: "",
  estado: "PUBLISHED",
},
{
  id: 905,
  organizador_id: 502,
  lugar_id: 701,
  categoria_id: 2,
  titulo: "Cumbia Inmersiva",
    slug: "cumbia-inmersiva",
  subtitulo: "",
  descripcion: "<p>Una experiencia inmersiva de cumbia con iluminación, escenografía y orquestas en vivo.</p>",
  start_time: "2025-11-22T21:00:00Z",
  cover_url: require("@/src/core/assets/events/alice-park/event3.png"),
  attendeesCount: 0,
   totalSales: 12589.8,
    ticketsSold: 365,
  tickets: [
    { id: "ticket-general-cumbia-inmersiva", name: "Entrada General", price: 55, currency: "Bs.", available: true, isSoldOut: false },
  ],
  sectorImageUrl: "",
  spotifyPlaylistUrl: "https://open.spotify.com/playlist/37i9dQZF1DWT1viuVscXm2", // Cumbia playlist 🎧 :contentReference[oaicite:5]{index=5}
  youtubeVideoUrl: "",
  estado: "PUBLISHED",
},

{
  id: 906,
  organizador_id: 500,
  lugar_id: 705,
  categoria_id: 2,
  titulo: "Modo Cumbia",
    slug: "modo-cumbia",
  subtitulo: "",
  descripcion: "<p>🎶 Una noche dedicada a la cumbia y los ritmos del litoral. DJs invitados y orquesta en vivo para no parar de bailar.<br/><br/>Ambiente festivalero, luces y mucho ritmo. ¡Trae a tu gente!</p>",
  start_time: "2025-11-28T22:00:00Z",
  cover_url: require("@/src/modules/home/assets/modo-cumbia.png"),
  attendeesCount: 350,
  totalSales: 22750,
  ticketsSold: 275,
  tickets: [
    { id: "modo-general", name: "GENERAL", price: 50, currency: "Bs.", available: true, isSoldOut: false },
    { id: "modo-vip", name: "VIP", price: 150, currency: "Bs.", available: true, isSoldOut: false },
  ],
  sectorImageUrl: "",
  spotifyPlaylistUrl: "https://open.spotify.com/playlist/37i9dQZF1DX8yLfjPY8emY?utm_source=generator",
  youtubeVideoUrl: "",
  estado: "PUBLISHED",
},

{
  id: 907,
  organizador_id: 500,
  lugar_id: 705,
  categoria_id: 2,
  titulo: "B-RLIN en Concierto",
    slug: "brlin",
  subtitulo: "",
  descripcion: "<p>🎸 B-RLIN trae riffs y energía rockera a Euphoria. Una noche con power, buenos mosh y clásicos que no pueden faltar.<br/><br/>¡Llega temprano y asegura tu lugar!</p>",
  start_time: "2025-10-05T21:30:00Z",
  cover_url: require("@/src/modules/home/assets/brlin.png"),
  attendeesCount: 420,
  totalSales: 37800,
  ticketsSold: 300,
  tickets: [
    { id: "brlin-general", name: "GENERAL", price: 70, currency: "Bs.", available: true, isSoldOut: false },
    { id: "brlin-vip", name: "VIP", price: 200, currency: "Bs.", available: true, isSoldOut: false },
    { id: "brlin-meet", name: "MEET & GREET", price: 350, currency: "Bs.", available: true, isSoldOut: false },
  ],
  sectorImageUrl: "",
  spotifyPlaylistUrl: "https://open.spotify.com/embed/playlist/37i9dQZF1DZ06evO4dbcMX?utm_source=generator&theme=0",
  youtubeVideoUrl: "",
  estado: "PUBLISHED",
},

{
  id: 908,
  organizador_id: 500,
  lugar_id: 705,
  categoria_id: 2,
  titulo: "Reik en Concierto",
    slug: "reik",
  subtitulo: "",
  descripcion: "<p>💔 Reik llega con sus baladas y éxitos para una velada romántica y emotiva. No te pierdas los clásicos que todos cantan a coro.<br/><br/>Una noche de voces, piano y sentimiento.</p>",
  start_time: "2025-06-06T21:00:00Z",
  cover_url: require("@/src/modules/home/assets/reik.png"),
  attendeesCount: 800,
  totalSales: 96000,
  ticketsSold: 600,
  tickets: [
    { id: "reik-general", name: "GENERAL", price: 100, currency: "Bs.", available: true, isSoldOut: false },
    { id: "reik-vip", name: "VIP", price: 300, currency: "Bs.", available: true, isSoldOut: false },
    { id: "reik-platea", name: "PLATEA", price: 180, currency: "Bs.", available: true, isSoldOut: false },
  ],
  sectorImageUrl: "",
  spotifyPlaylistUrl: "https://open.spotify.com/playlist/37i9dQZF1DX0XUsuxWHRQd?utm_source=generator",
  youtubeVideoUrl: "",
  estado: "PUBLISHED",
},

{
  id: 909,
  organizador_id: 500,
  lugar_id: 705,
  categoria_id: 2,
  titulo: "Oktober Fest",
    slug: "oktober-fest",
  subtitulo: "",
  descripcion: "<p>🍺 Oktober Fest vuelve con cervezas, food trucks y música en vivo. Ambiente para compartir con amigos y brindar como corresponde.<br/><br/>Trae tu mejor onda y gana premios.</p>",
  start_time: "2025-11-25T18:30:00Z",
  cover_url: require("@/src/modules/home/assets/oktober-fest.png"),
  attendeesCount: 600,
  totalSales: 42000,
  ticketsSold: 600,
  tickets: [
    { id: "oktober-general", name: "GENERAL", price: 70, currency: "Bs.", available: true, isSoldOut: false },
    { id: "oktober-vaso", name: "TICKET + VASO", price: 120, currency: "Bs.", available: true, isSoldOut: false },
  ],
  sectorImageUrl: "",
  spotifyPlaylistUrl: "https://open.spotify.com/embed/playlist/3HVzd3HwLK56sRSSVxhFVN?utm_source=generator",
  youtubeVideoUrl: "",
  estado: "PUBLISHED",
},

{
  id: 910,
  organizador_id: 501,
  lugar_id: 702,
  categoria_id: 2,
  titulo: "Pink Friday",
    slug: "pink-friday",
  subtitulo: "",
  descripcion: "<p>🌸 Pink Friday: fiesta pop y electrónica para cerrar la temporada en NOMA. DJs, visuals y una pista que no para.<br/><br/>Dress code: pink vibes.</p>",
  start_time: "2025-12-03T22:00:00Z",
  cover_url: require("@/src/modules/home/assets/pink-friday.png"),
  attendeesCount: 300,
  totalSales: 19500,
  ticketsSold: 250,
  tickets: [
    { id: "pink-general", name: "GENERAL", price: 60, currency: "Bs.", available: true, isSoldOut: false },
    { id: "pink-vip", name: "VIP", price: 140, currency: "Bs.", available: true, isSoldOut: false },
  ],
  sectorImageUrl: "",
  spotifyPlaylistUrl: "https://open.spotify.com/embed/playlist/4pnXzlKEJwkjsB6JmhscTi?utm_source=generator&theme=0",
  youtubeVideoUrl: "",
  estado: "PUBLISHED",
},

{
  id: 911,
  organizador_id: 502,
  lugar_id: 701,
  categoria_id: 2,
  titulo: "El Circo - Capítulo Final",
    slug: "el-circo",
  subtitulo: "",
  descripcion: "<p>🎪 El Circo llega a Alice Park con su capítulo final: acrobacias, magia y espectáculo para toda la familia.<br/><br/>Última función, entradas limitadas.</p>",
  start_time: "2025-08-23T19:00:00Z",
  cover_url: require("@/src/modules/home/assets/circo-capitulo-final.jpg"),
  attendeesCount: 700,
  totalSales: 42000,
  ticketsSold: 420,
  tickets: [
    { id: "circo-general", name: "GENERAL", price: 60, currency: "Bs.", available: true, isSoldOut: false },
    { id: "circo-familiar", name: "FAMILIAR (4)", price: 200, currency: "Bs.", available: true, isSoldOut: false },
  ],
  sectorImageUrl: "",
  spotifyPlaylistUrl: "", // no playlist (evento familiar/teatro)
  youtubeVideoUrl: "",
  estado: "PUBLISHED",
},

{
  id: 912,
  organizador_id: 502,
  lugar_id: 706,
  categoria_id: 2,
  titulo: "Fexco Negocios",
    slug: "fexco",
  subtitulo: "",
  descripcion: "<p>🤝 Fexco Negocios — conferencias, networking.</p>",
  start_time: "2025-11-20T22:30:00Z",
  cover_url: require("@/src/modules/home/assets/fexco.jpg"),
  attendeesCount: 250,
  totalSales: 12500,
  ticketsSold: 250,
  tickets: [
    { id: "fexco-general", name: "GENERAL", price: 50, currency: "Bs.", available: true, isSoldOut: false },
  ],
  sectorImageUrl: "",
  spotifyPlaylistUrl: "",
  youtubeVideoUrl: "",
  estado: "PUBLISHED",
},

{
  id: 913,
  organizador_id: 502,
  lugar_id: 701,
  categoria_id: 2,
  titulo: "Doble Vía en Vivo",
    slug: "doble-via",
  subtitulo: "",
  descripcion: "<p>🔥 Doble Vía en Vivo: orquesta, cumbia moderna y mucho baile. Ven con ganas de mover las caderas.<br/><br/>Entradas limitadas.</p>",
  start_time: "2025-11-29T21:30:00Z",
  cover_url: require("@/src/modules/home/assets/doble-via.png"),
  attendeesCount: 500,
  totalSales: 32500,
  ticketsSold: 500,
  tickets: [
    { id: "doble-general", name: "GENERAL", price: 50, currency: "Bs.", available: true, isSoldOut: false },
    { id: "doble-vip", name: "VIP", price: 150, currency: "Bs.", available: true, isSoldOut: false },
  ],
  sectorImageUrl: "",
  spotifyPlaylistUrl: "https://open.spotify.com/playlist/37i9dQZF1DWT1viuVscXm2?utm_source=generator",
  youtubeVideoUrl: "",
  estado: "PUBLISHED",
},

{
  id: 914,
  organizador_id: 503,
  lugar_id: 701,
  categoria_id: 2,
  titulo: "Levitar Night",
    slug: "levitar",
  subtitulo: "",
  descripcion: "<p>🌌 Levitar Night: una curaduría musical que mezcla electrónica y downtempo para una noche sofisticada.</p>",
  start_time: "2025-11-30T23:00:00Z",
  cover_url: require("@/src/modules/home/assets/levitar.png"),
  attendeesCount: 220,
  totalSales: 14000,
  ticketsSold: 175,
  tickets: [
    { id: "levitar-general", name: "GENERAL", price: 60, currency: "Bs.", available: true, isSoldOut: false },
    { id: "levitar-vip", name: "VIP", price: 120, currency: "Bs.", available: true, isSoldOut: false },
  ],
  sectorImageUrl: "",
  spotifyPlaylistUrl: "https://open.spotify.com/embed/playlist/3ybZkcoA09pYekp0DIo1OP?utm_source=generator&theme=0",
  youtubeVideoUrl: "",
  estado: "PUBLISHED",
},

{
  id: 917,
  organizador_id: 501,
  lugar_id: 702,
  categoria_id: 2,
  titulo: "It's Britney",
    slug: "its-britney",
  subtitulo: "*****",
  descripcion: "<p>🤍 Noche BRANCA: elegante, chic y con una pista lista para bailar hasta tarde. Dress code: total white.</p>",
  start_time: "2025-12-22T21:30:00Z",
  cover_url: require("@/src/core/assets/events/noma/event3.png"),
  attendeesCount: 380,
  totalSales: 26600,
  ticketsSold: 380,
  tickets: [
    { id: "branca-general", name: "GENERAL", price: 70, currency: "Bs.", available: true, isSoldOut: false },
    { id: "branca-vip", name: "VIP", price: 140, currency: "Bs.", available: true, isSoldOut: false },
  ],
  sectorImageUrl: "",
  spotifyPlaylistUrl: "https://open.spotify.com/playlist/37i9dQZF1DX0XUsuxWHRQd?utm_source=generator",
  youtubeVideoUrl: "",
  estado: "PUBLISHED",
},

{
  id: 918,
  organizador_id: 501,
  lugar_id: 702,
  categoria_id: 2,
  titulo: "Proyecto N",
    slug: "proyecto-n",
  subtitulo: "",
  descripcion: "<p>Proyecto N: la fiesta mas destructiva donde tu eres el centro del mundo.</p>",
  start_time: "2026-03-26T21:00:00Z",
  cover_url: require("@/src/core/assets/events/noma/event2.png"),
  attendeesCount: 320,
  totalSales: 19200,
  ticketsSold: 320,
  tickets: [
    { id: "latina-general", name: "GENERAL", price: 60, currency: "Bs.", available: true, isSoldOut: false },
    { id: "latina-vip", name: "VIP", price: 120, currency: "Bs.", available: true, isSoldOut: false },
  ],
  sectorImageUrl: "",
  spotifyPlaylistUrl: "https://open.spotify.com/embed/playlist/4IGBvF2yCCfT6cO3zS3P0a?utm_source=generator&theme=0",
  youtubeVideoUrl: "",
  estado: "PUBLISHED",
},

// Teatro Achá / funciones culturales (organizador Broadway o Danzares según evento)
{
  id: 919,
  organizador_id: 499,
  lugar_id: 703,
  categoria_id: 1,
  titulo: "SHOW ¡Ven, canta y baila!",
    slug: "show-wilson",
  subtitulo: "Sing • Mentiras el musical • El Mago de Oz",
  descripcion: "<p>🎭 ¡Un espectáculo para toda la familia! Voces, baile y escenas inolvidables en una puesta en escena única. Invitado especial: Broadway Teatro Musical.<br/><br/>Funciones 18 y 19 de diciembre — no te lo pierdas.</p>",
  start_time: "2025-12-18T19:30:00Z",
  cover_url: require("@/src/core/assets/events/broadway/event1.png"),
  attendeesCount: 400,
  totalSales: 28000,
  ticketsSold: 350,
  tickets: [
    { id: "show-general", name: "PLATEA GENERAL", price: 80, currency: "Bs.", available: true, isSoldOut: false },
    { id: "show-vip", name: "PLATEA VIP", price: 180, currency: "Bs.", available: true, isSoldOut: false },
  ],
  sectorImageUrl: "",
  spotifyPlaylistUrl: "", // teatro -> sin playlist
  youtubeVideoUrl: "",
  estado: "PUBLISHED",
},

{
  id: 920,
  organizador_id: 498,
  lugar_id: 703,
  categoria_id: 1,
  titulo: "Querencias – Temporada 2025",
    slug: "querencias",
  subtitulo: "Paola Rivero",
  descripcion: "<p>🌾 'Querencias' nos trae paisajes, danza y tradición en un montaje profundamente emotivo y visualmente hermoso.<br/><br/>Funciones 14 y 15 de mayo, Teatro Achá.</p>",
  start_time: "2025-05-14T19:30:00Z",
  cover_url: require("@/src/core/assets/events/danzares/event2.png"),
  attendeesCount: 250,
  totalSales: 12500,
  ticketsSold: 200,
  tickets: [
    { id: "querencias-general", name: "GENERAL", price: 60, currency: "Bs.", available: true, isSoldOut: false },
  ],
  sectorImageUrl: "",
  spotifyPlaylistUrl: "", // danza -> sin playlist
  youtubeVideoUrl: "",
  estado: "PUBLISHED",
},

{
  id: 921,
  organizador_id: 498,
  lugar_id: 703,
  categoria_id: 1,
  titulo: "Bolivia 200 Años de Libertad",
    slug: "bolivia-200",
  subtitulo: "Paola Rivero",
  descripcion: "<p>🇧🇴 Celebrando 200 años con un espectáculo coreográfico que fusiona tradición y contemporaneidad. Una función imperdible en Teatro Achá.</p>",
  start_time: "2025-10-14T19:30:00Z",
  cover_url: require("@/src/core/assets/events/danzares/event1.png"),
  attendeesCount: 500,
  totalSales: 35000,
  ticketsSold: 350,
  tickets: [
    { id: "bolivia200-general", name: "GENERAL", price: 100, currency: "Bs.", available: true, isSoldOut: false },
    { id: "bolivia200-vip", name: "PLATEA VIP", price: 250, currency: "Bs.", available: true, isSoldOut: false },
  ],
  sectorImageUrl: "",
  spotifyPlaylistUrl: "", // danza -> sin playlist
  youtubeVideoUrl: "",
  estado: "PUBLISHED",
},

{
  id: 922,
  organizador_id: 497,
  lugar_id: 704,
  categoria_id: 1,
  titulo: "El Palacio Suena",
    slug: "palacio-suena",
  subtitulo: "Una casa, un corazón",
  descripcion: "<p>🏛️ 'El Palacio Suena' abre sus puertas con muestras de arte, música y performances. Un encuentro íntimo con la cultura local.</p>",
  start_time: "2025-11-20T19:00:00Z",
  cover_url: require("@/src/core/assets/events/fundacion-patino/event2.png"),
  attendeesCount: 120,
  totalSales: 3600,
  ticketsSold: 60,
  tickets: [
    { id: "palacio-general", name: "GENERAL", price: 60, currency: "Bs.", available: true, isSoldOut: false },
  ],
  sectorImageUrl: "",
  spotifyPlaylistUrl: "", // exposición cultural -> sin playlist
  youtubeVideoUrl: "",
  estado: "PUBLISHED",
},

{
  id: 923,
  organizador_id: 497,
  lugar_id: 704,
  categoria_id: 1,
  titulo: "Presentación de Libro: ¿Dónde carajos está Litovchenko?",
    slug: "litovchenko",
  subtitulo: "Los hermanos Loayza",
  descripcion: "<p>📚 Presentación editorial y conversación con los autores. Ingreso libre en el Salón Principal del Palacio Portales.</p>",
  start_time: "2025-12-05T19:00:00Z",
  cover_url: require("@/src/core/assets/events/fundacion-patino/event1.png"),
  attendeesCount: 80,
  totalSales: 0,
  ticketsSold: 0,
  tickets: [],
  sectorImageUrl: "",
  spotifyPlaylistUrl: "", // libro -> sin playlist
  youtubeVideoUrl: "",
  estado: "PUBLISHED",
},

{
  id: 924,
  organizador_id: 499,
  lugar_id: 703,
  categoria_id: 1,
  titulo: "Hamilton – El Musical (Gira Bolivia)",
    slug: "hamilton-musical",
  subtitulo: "",
  descripcion: "<p>🎭 Hamilton — el espectáculo musical que marcó una era. Próximamente en varias ciudades del país. Detalles de venta por Broadway.</p>",
  start_time: "2026-03-01T19:30:00Z",
  cover_url: require("@/src/core/assets/events/broadway/event2.png"),
  attendeesCount: 0,
  totalSales: 0,
  ticketsSold: 0,
  tickets: [],
  sectorImageUrl: "",
  spotifyPlaylistUrl: "", // musical -> sin playlist
  youtubeVideoUrl: "",
  estado: "PUBLISHED",
},

  ],
  intereses_usuario: [
    { usuario_id: 1001, categorias_id: 1 },
    { usuario_id: 1001, categorias_id: 2 },
    { usuario_id: 1001, categorias_id: 4 },
  ],
  notificaciones: [
    {
      id: 30001,
      usuario_id: 1001,
      tipo: "EVENT_REMINDER",
      image: require("@/src/core/assets/events/alice-park/event4.jpg"),
      titulo: "Tu evento Sunset Beats Alice Park empieza pronto",
      cuerpo: "Preparate para disfrutar de la noche en Alice Park",
      data: { evento_id: 901, start_time: "2025-01-20T21:00:00" },
      creado_en: "2025-01-20T15:00:00Z",
      leido_en: null,
    },
    {
      id: 30002,
      usuario_id: 1001,
      tipo: "FAVORITE_EVENT_UPDATE",
      image: require("@/src/core/assets/events/noma/profile.png"),
      titulo: "Tech Meetup Cochabamba actualizo sus detalles",
      cuerpo: "Se modifico la hora de inicio del evento",
      data: { evento_id: 902 },
      creado_en: "2025-02-01T12:30:00Z",
      leido_en: "2025-02-02T08:05:00Z",
    },
    {
      id: 30003,
      usuario_id: 1001,
      tipo: "ticket_available",
      image: require("@/src/core/assets/events/fexco/event2.png"),
      titulo: "Tu TICKET para TECH MEETUP COCHABAMBA se encuentra disponible",
      cuerpo: "Asegura tu lugar antes de que se agoten",
      data: { evento_id: 902 },
      creado_en: "2025-12-11T07:00:00Z",
      leido_en: null,
    },
    {
      id: 30004,
      usuario_id: 1001,
      tipo: "new_event",
      image: require("@/src/core/assets/events/noma/profile.png"),
      titulo: "NOMA acaba de publicar un evento que podría interesarte",
      cuerpo: "Tech Meetup Cochabamba",
      data: { evento_id: 902 },
      creado_en: "2025-12-11T03:00:00Z",
      leido_en: null,
    },
    {
      id: 30005,
      usuario_id: 1001,
      tipo: "opinion_request",
      image: require("@/src/core/assets/events/alice-park/profile.jpg"),
      titulo: "Nos interesa tu Opinión!",
      cuerpo: "¿Qué tal estuvo Sunset Beats Alice Park?",
      data: { evento_id: 901, rating: 0 },
      creado_en: "2025-12-10T12:00:00Z",
      leido_en: null,
    },
    {
      id: 30006,
      usuario_id: 1001,
      tipo: "event_update",
      image: require("@/src/core/assets/events/alice-park/event5.jpg"),
      titulo: "Alice Park actualizó detalles sobre Sunset Beats Alice Park",
      cuerpo: "Se añadieron nuevos artistas y foodtrucks",
      data: { evento_id: 901 },
      creado_en: "2025-12-09T09:00:00Z",
      leido_en: null,
    },
    {
      id: 30007,
      usuario_id: 1001,
      tipo: "sold_out",
      image: require("@/src/core/assets/events/alice-park/event4.jpg"),
      titulo: "Sunset Beats Alice Park - SOLD OUT",
      cuerpo: "Gracias por tu interés, pronto más experiencias inolvidables!",
      data: { evento_id: 901 },
      creado_en: "2025-12-07T18:00:00Z",
      leido_en: null,
    },
    {
      id: 30008,
      usuario_id: 1001,
      tipo: "tickets_low",
      image: require("@/src/core/assets/events/fexco/event2.png"),
      titulo: "Tech Meetup Cochabamba tickets por agotarse!",
      cuerpo: "Quedan pocas entradas, no te quedes afuera",
      data: { evento_id: 902 },
      creado_en: "2025-12-04T10:00:00Z",
      leido_en: null,
    },
  ],
  organizer_reviews: [
    {
      id: 40001,
      organizer_id: 502,
      eventId: 901,
      userName: "Carla Morales",
      userAvatar: require("@/src/core/assets/profiles/profile2.png"),
      rating: 5,
      date: "2025-01-22",
      comment: "Sunset Beats fue increíble, buena música y ambiente!",
    },
    {
      id: 40002,
      organizer_id: 502,
      eventId: 901,
      userName: "Luis Sanchez",
      userAvatar: require("@/src/core/assets/profiles/profile1.png"),
      rating: 4,
      date: "2025-01-21",
      comment: "Excelente organización, faltó un poco más de señalización.",
    },
    {
      id: 40003,
      organizer_id: 502,
      eventId: 902,
      userName: "Andrea Rodriguez",
      userAvatar: require("@/src/core/assets/profiles/profile3.png"),
      rating: 5,
      date: "2025-02-11",
      comment: "Tech Meetup estuvo genial, charlas muy útiles y networking!",
    },
    {
      id: 40004,
      organizer_id: 502,
      eventId: 902,
      userName: "Diego Martinez",
      userAvatar: require("@/src/core/assets/profiles/profile4.png"),
      rating: 3,
      date: "2025-02-10",
      comment: "Buen contenido, pero el audio pudo estar mejor.",
    },
  ],
  // Curated sections for home/collections, using canonical numeric event IDs
  curated: {
    featured: [901, 924, 912, 914],
    popular: [913, 919, 907, 920, 904],
    nearby: [914, 921, 909, 903, 917],
    forYou: [920, 907, 912, 901, 914, 924, 913, 918, 922, 909],
    banner: [901, 924, 912, 914],
    normal: [901, 902, 903, 904, 905, 906, 907, 908, 909, 910, 912, 913, 914, 916, 917, 918, 919, 920, 921, 922, 923, 924],
    sponsored: [901, 924, 912, 914],
  },
} as const;

export const PRIMARY_TEST_USER = TEST_DATABASE.usuarios[0];

export const PRIMARY_TEST_USER_INTEREST_IDS = TEST_DATABASE.intereses_usuario
  .filter((interest) => interest.usuario_id === PRIMARY_TEST_USER.id)
  .map((interest) => interest.categorias_id);

type CategoryName = (typeof TEST_DATABASE.categorias)[number]["nombre"];

export const PRIMARY_TEST_USER_INTERESTS = PRIMARY_TEST_USER_INTEREST_IDS
  .map((categoryId) => TEST_DATABASE.categorias.find((category) => category.id === categoryId)?.nombre)
  .filter((nombre): nombre is CategoryName => Boolean(nombre));
